controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

welcome:
    path: /
    controller: App\Controller\welcomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

landing:
    path: /landing
    controller: App\Controller\userController::index

sujets:
    path: /sujets
    controller: App\Controller\SujetController::index

reponses:
    path: /reponses
    controller: App\Controller\ReponseController::index